name: Test
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-check:
    name: runner / markuplint (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-check
          level: info
          locale: "US"

  test-pr-check:
    if: github.event_name == 'pull_request'
    name: runner / markuplint (github-pr-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          level: warning
          locale: "US"
          workdir: ./test-subproject/

  test-pr-review:
    if: github.event_name == 'pull_request'
    name: runner / markuplint (github-pr-review)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        continue-on-error: true
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
          locale: "US"
          filter_mode: file
          fail_on_error: true
      - name: check the exit code
        if: ${{ !success() }}
        run: echo 'The previous step should fail' && exit 1

  test-sarif:
    name: runner / markuplint (sarif)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          reporter: sarif
          locale: "US"
